# docker-compose file creates volumes for the program to use.
services:
  nest_js_api:
    container_name: "scheduling-app-server"
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/home/victor-j-wilson/projects2/SchedulingApp/scheduling-app-server
    environment:
      NODE_ENV: development
    

  mongodb:
    hostname: mongodb
    image: mongodb/mongodb-atlas-local
    environment:
      MONGODB_INITDB_ROOT_USERNAME: '${DB_USERNAME}'
      MONGODB_INITDB_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - 27019:27017
    volumes:
      - data:/data/db 
      - config:/data/configdb

volumes:
  data:
  config:






