# docker-compose file creates volumes for the program to use.
version: '3.8'
services:
  activity_tracker_app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/home/victor-j-wilson/projects2/SchedulingApp/scheduling-app-server
      
    environment:
      NODE_ENV: dev
    command: npm run start:dev
    depends_on:
      - mongodb
  
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${DB_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - 27018:27017

volumes:
 data:
 config:



